name: Generate Ephemeris Data

on:
  # workflow_dispatch:  # Manual trigger
  # schedule:
    # Run every Monday at 9 AM UTC
    # - cron: '0 9 * * 1'
  push:
    branches: [main]
    paths:
      - 'app/api/generate-ephemeris/**'
      - '.github/workflows/generate-ephemeris.yml'

jobs:
  generate-ephemeris:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate ephemeris for the week
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NODE_ENV: production
        run: |
          # Get current date
          CURRENT_DATE=$(date +%Y-%m-%d)
          echo "Generating ephemeris for week starting: $CURRENT_DATE"
          
          # Generate for next 7 days
          for i in {0..6}; do
            # Calculate date for each day
            TARGET_DATE=$(date -d "$CURRENT_DATE + $i days" +%Y-%m-%d)
            DAY=$(date -d "$TARGET_DATE" +%d)
            MONTH=$(date -d "$TARGET_DATE" +%m)
            YEAR=$(date -d "$TARGET_DATE" +%Y)
            
            echo "Generating ephemeris for: $TARGET_DATE (Day: $DAY, Month: $MONTH, Year: $YEAR)"
            
            # Call the API endpoint
            curl -X POST https://programming-ephemerides.vercel.app/api/generate-ephemeris \
              -H "Content-Type: application/json" \
              -d "{\"day\": $DAY, \"month\": $MONTH, \"year\": $YEAR}" \
              --max-time 30 \
              --retry 3 \
              --retry-delay 5
            
            echo "Completed for $TARGET_DATE"
            
            # Wait a bit between requests to avoid rate limiting
            sleep 2
          done
          
          echo "Ephemeris generation completed for the week!"

      - name: Verify generation
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: |
          echo "Verifying generated ephemeris..."
          TODAY=$(date +%d)
          MONTH=$(date +%m)
          RESPONSE=$(curl -s "https://programming-ephemerides.vercel.app/api/generate-ephemeris?day=$TODAY&month=$MONTH")
          echo "$RESPONSE" | jq '.' || { echo "API did not return valid JSON!"; echo "$RESPONSE"; exit 1; }
          echo "Verification completed!"

      - name: Notify completion
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Ephemeris generation completed successfully!"
          else
            echo "❌ Ephemeris generation failed!"
            exit 1
          fi 